# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/choffmeister/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/choffmeister/{{ .ProjectName }}:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "0.0.0-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
